sudo: required
services:
- docker
env:
  global:
  - DOCKER_HUB_USER=vbenji
  - secure: a4YhsMsS6CsVjEOlGDVuhvA2MGNKy6ZEnFLb/0KJn7wa+fJFX3VsK/jOkuq1ITYeaTs8oB00BQHR1kJptXhk2EKRI23Sw+u88V841syF2cQhWPMdcKtuH5drQCCYRFtAvw3oq9lSuVId2DmQ9L1nKucnhGR1XfXf92JLvyQsmfA2G2hd5ObykYO/KL4YFUNCq+IgB3O942QukSc1e/maYrw14+1KEmdZLFFEmSpSugUSkad5b54+1FRNel7H72wHGn4Pn99byqqWW1NaE3X1dsmqRVYFQEVWmoHMv4Lj/HOYDfLtVcEUCx6DbpOsfmzdQlR/vXAD1sVhjUeRr9SM3giBcS8Za6ND6MhPrM//BOHBdWg8NTGjmizA2VuB5Nx59ipqrP7pEgIsYZdB//nWJdgz3NyrLfHzz3iDqfCCBrnMXChthcZZHMmf7SskjMk2sD6Nh3NpGo9jy6QlM3pu9eigh5FKgBzQq9knVp4XYO3GCDtBk1Yp8xSBnNGBJ2i6m1QmJ1qpyHJ7fkakhSLryP8rZjxiHS02ESAEzJygQZtQ3ol/qqizWHYUavB2TjwupXBZC154NQUtzmbtdLhph7vcC/FsBNMd0RvqAueCccIcf+CN6zykNvQN4CMkyYY/cK9I1tsdXcX+Ugv+Q5NapgjZnaq83uavumIlWlPdHUw=
script:
- docker-compose build
before_deploy:
- docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
deploy:
  provider: script
  script: docker-compose push
  on:
    branch: master
